color= input("enter a color")
pluralNoun = input("enter a plural noun : ")
celebrity = input("enter a celebrity : ")
print("Roses are ", color)
print(pluralNoun+ " are blue")
print("i know im meant to be with ", celebrity)